name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install git+https://github.com/openai/CLIP.git
      - name: Lint with Ruff
        run: |
          ruff --ignore=F401,E501 --format=github --target-version=py37 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          python -m pytest -W ignore::DeprecationWarning